controllers:
    resource: ../src/Controller/
    type: attribute

route_accueil:
    path: /accueil
    controller: App\Controller\IndexController::index


#annonces

annonceLister:
    path: /annonce/lister/{idType}
    controller: App\Controller\AnnonceController::listerAnnonce

annonceConsulter:
    path: /annonce/consulter/{id}
    controller: App\Controller\AnnonceController::consulterAnnonce

annonceAjouter:
    path: /annonce/ajouter/
    controller: App\Controller\AnnonceController::ajouterAnnonce

annonceModifier:
    path: /annonce/modifier/{id}
    controller: App\Controller\AnnonceController::modifierAnnonce

toggleArchive:
    path: /toggle-archive/{id}
    controller: App\Controller\AnnonceController::toggleArchive


#evenement
evenementAjouter:
    path: /evenement/ajouter/
    controller: App\Controller\EvenementController::ajouterEvenement

evenementLister:
    path: /evenement/lister/
    controller: App\Controller\EvenementController::listerEvenement


#connexion

app_logout:
    path: /logout
    methods: GET

app_login:
    path: /login
    controller: App\Controller\LoginController::index

inscription:
    path: /inscription
    controller: App\Controller\RegistrationController::register


#compte

compteLister:
    path: /compte/lister
    controller: App\Controller\AdminController::listerCompte

compteModifier:
    path: /compte/modifier/{idCompte}
    controller: App\Controller\CompteController::modifierCompte

profil:
    path: /profil/{id}
    controller: App\Controller\CompteController::consulterCompte

mesAnnonces:
    path: /mesAnnonces/{idCompte}
    controller: App\Controller\CompteController::listerMesAnnonce

reset-password:
    path: /reset-password



#admin

admin:
    path: /admin
    controller: App\Controller\IndexController::admin

annoncesAdmin:
    path: admin/annonces
    controller: App\Controller\AdminController::listerToutesLesAnnonces

compteModifierAdmin:
    path: /admin/compte/modifier/{id}
    controller: App\Controller\AdminController::modifierCompteAdmin

domaineAjouter:
    path: admin/domaine/ajouter
    controller: App\Controller\DomaineController::ajouterDomaine

adminAjouter:
    path: admin/create
    controller: App\Controller\AdminController::createAdmin



#error
accessDenied: 
    path: /error/access_denied
    controller: 'App\Controller\ErrorController::showAccessDenied'


errorAuthentification: 
    path: /error/error_authentification
    controller: 'App\Controller\ErrorController::showErrorAuthentification'

#page statique

mentionsLegales:
    path: /mentions_legales
    controller: App\Controller\PageJuridiqueController::mentionsLegales

politiqueConfidentialite:
    path: /politique_confidentialite
    controller: App\Controller\PageJuridiqueController::politiqueConfidentialite
