controllers:
    resource: ../src/Controller/
    type: attribute

route_accueil:
    path: /accueil
    controller: App\Controller\IndexController::index


#annonces

annonceLister:
    path: /annonce/lister/
    controller: App\Controller\AnnonceController::listerAnnonce

annonceConsulter:
    path: /annonce/consulter/{id}
    controller: App\Controller\AnnonceController::consulterAnnonce

annonceAjouter:
    path: /annonce/ajouter/
    controller: App\Controller\AnnonceController::ajouterAnnonce




typeLister:
    path: /type/lister
    controller: App\Controller\TypeController::listerType


#connexion

app_logout:
    path: /logout
    methods: GET

app_login:
    path: /login
    controller: App\Controller\LoginController::index

inscription:
    path: /inscription
    controller: App\Controller\RegistrationController::register

