controllers:
    resource: ../src/Controller/
    type: attribute

route_accueil:
    path: /accueil
    controller: App\Controller\IndexController::index

admin:
    path: /admin
    controller: App\Controller\IndexController::admin


#annonces

annonceLister:
    path: /annonce/lister/{idType}
    controller: App\Controller\AnnonceController::listerAnnonce

annonceConsulter:
    path: /annonce/consulter/{id}
    controller: App\Controller\AnnonceController::consulterAnnonce

annonceAjouter:
    path: /annonce/ajouter/
    controller: App\Controller\AnnonceController::ajouterAnnonce


#evenement
evenementAjouter:
    path: /evenement/ajouter/
    controller: App\Controller\EvenementController::ajouterEvenement

evenementLister:
    path: /evenement/lister/
    controller: App\Controller\EvenementController::listerEvenement





typeLister:
    path: /type/lister
    controller: App\Controller\TypeController::listerType


#connexion

app_logout:
    path: /logout
    methods: GET

app_login:
    path: /login
    controller: App\Controller\LoginController::index

inscription:
    path: /inscription
    controller: App\Controller\RegistrationController::register


#compte

compteLister:
    path: /compte/lister
    controller: App\Controller\CompteController::listerCompte

profil:
    path: /profil/{id}
    controller: App\Controller\CompteController::consulterCompte

mesAnnonces:
    path: /mesAnnonces/{idCompte}
    controller: App\Controller\CompteController::listerAnnonce
   
